# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-08 08:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 8, 8, 48, 44, 751774, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
